# Generated by Django 4.2.20 on 2025-05-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mode',
            options={'ordering': ['name'], 'verbose_name': 'Mode of Payment', 'verbose_name_plural': 'Modes of Payment'},
        ),
    ]
