# Generated by Django 4.2.20 on 2026-01-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_hotel_status_remove_insurance_status_and_more'),
        ('payments', '0003_paymentreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='services.servicelist'),
        ),
    ]
