# Generated by Django 4.2.20 on 2026-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentreceived_service'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentreceived',
            index=models.Index(fields=['booking', 'service', 'approved'], name='payment_bk_svc_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceived',
            index=models.Index(fields=['approved', 'booking'], name='payment_appr_bk_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceived',
            index=models.Index(fields=['-created_at'], name='payment_created_idx'),
        ),
    ]
