# Generated by Django 4.2.20 on 2025-05-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('travel_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SightSeeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sightseeing_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('travel_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('travel_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_booking_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visas', to='bookings.booking')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode')),
            ],
        ),
    ]
