# Generated by Django 4.2.20 on 2025-05-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visa_suppliers', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_suppliers', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='services.carrier'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_suppliers', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sightseeings', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode'),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sightseeing_suppliers', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='passport',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='passports', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='passport',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode'),
        ),
        migrations.AddField(
            model_name='passport',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passport_suppliers', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insurances', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_suppliers', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hotels', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.mode'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_suppliers', to='suppliers.supplier'),
        ),
    ]
