# Generated by Django 4.2.20 on 2025-05-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['name'], 'verbose_name': 'Carrier', 'verbose_name_plural': 'Carriers'},
        ),
    ]
