# Generated by Django 4.2.20 on 2025-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_carrier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='passport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
