# Generated by Django 4.2.20 on 2025-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_hotel_attachment_hotel_notes_insurance_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='visa',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed')], default='draft', max_length=20),
        ),
    ]
