# Generated by Django 4.2.20 on 2025-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_hotel_status_insurance_status_passport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='visa',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Accounts'), ('processed', 'Processed'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
    ]
