# Generated by Django 4.2.20 on 2025-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_hotel_created_by_insurance_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='status',
        ),
        migrations.AddField(
            model_name='hotel',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurance',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurance',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passport',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passport',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visa',
            name='accounts_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visa',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
