# Generated by Django 4.2.20 on 2026-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_hotel_status_remove_insurance_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['accounts_processed', 'finished'], name='hotel_acct_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['booking', 'travel_type'], name='hotel_bk_travel_idx'),
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['accounts_processed', 'finished'], name='insurance_acct_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['accounts_processed', 'finished'], name='passport_acct_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='sightseeing',
            index=models.Index(fields=['accounts_processed', 'finished'], name='sightsee_acct_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='sightseeing',
            index=models.Index(fields=['booking', 'travel_type'], name='sightsee_bk_travel_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['accounts_processed', 'finished'], name='ticket_acct_finished_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['accounts_processed', 'finished'], name='transfer_acct_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['booking', 'travel_type'], name='transfer_bk_travel_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['accounts_processed', 'finished'], name='visa_acct_fin_idx'),
        ),
    ]
