# Generated by Django 4.2.20 on 2026-08-03 11:41
#
# STATE-ONLY: this migration emits no SQL.
#
# The seven service models moved onto a shared abstract base, whose foreign
# keys declare related_name as "%(class)ss" / "%(class)s_supplierss" instead of
# the literal "tickets" / "ticket_suppliers". Those expand to exactly the same
# accessor names, but the raw string is recorded in migration state, so the
# autodetector sees a difference and writes AlterField operations.
#
# related_name is a Python-side attribute; it is listed in Django's
# _field_should_be_altered() non-database attributes, so every operation below
# resolves to a no-op. Confirmed with:
#
#     python manage.py sqlmigrate services 0011
#
# which prints "-- (no-op)" for all fourteen. Safe to apply to production
# without locking or rebuilding anything.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_contact_person_supplier_email_and_more'),
        ('bookings', '0012_booking_booking_date_idx_and_more'),
        ('services', '0010_hotel_hotel_acct_fin_idx_hotel_hotel_bk_travel_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_suppliers', to='suppliers.supplier'),
        ),
    ]
