# Generated by Django 4.2.20 on 2025-05-27 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicelist'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='bookings', through='bookings.BookingService', to='services.servicelist'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.status'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingservice',
            unique_together={('booking', 'service')},
        ),
    ]
