# Generated by Django 4.2.20 on 2025-06-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_status_options_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accounts_done',
            field=models.BooleanField(default=False, verbose_name='Accounts Processed'),
        ),
    ]
