# Generated by Django 4.2.20 on 2025-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_accounts_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotels_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurances_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='passports_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sightseeings_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfers_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='visas_finished',
            field=models.BooleanField(default=False),
        ),
    ]
