# Generated by Django 4.2.20 on 2025-06-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('bookings', '0007_alter_booking_client_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bookings.status'),
        ),
    ]
