# Generated by Django 4.2.20 on 2025-06-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_hotel_created_by_insurance_created_by_and_more'),
        ('bookings', '0008_alter_booking_client_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicelist'),
        ),
    ]
