# Generated by Django 4.2.20 on 2025-06-26 10:35

import bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_contact_person_supplier_email_and_more'),
        ('services', '0009_remove_hotel_status_remove_insurance_status_and_more'),
        ('bookings', '0009_alter_bookingservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=bookings.models.booking_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicelist')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
    ]
