# Generated by Django 4.2.20 on 2025-11-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_bookingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='bookings.status'),
        ),
    ]
